version: 2.1

orbs:
  virtuaexecutors: virtuaorbs/executors@0.1.0
  virtuacommands: virtuaorbs/commands@0.3.0

jobs:
  surveillance-job:
    executor: virtuaexecutors/mongoruby_2-6-3
    steps:
      - virtuacommands/setup-ruby-environment
      - run:
          name: "Make a watch over the whole infrastructure to detect problems"
          command: |
            mkdir /tmp/surveillance
            bundle exec ruby watcher.rb > /tmp/surveillance/results.json
      - store_test_results:
          path: /tmp/surveillance
      - store_artifacts:
          path: /tmp/surveillance
          destination: surveillance

workflows:
  version: 2.1
  watch:
    triggers:
      - schedule:
          cron: 0,10,20,30,40,50 * * * *
          filters:
            branches:
              only:
                - master
                - issue/cron
    jobs:
      - surveillance-job
  deploy:
    jobs:
      - surveillance-job