version: 2.1
orbs:
  virtuaexecutors: virtuaorbs/executors@0.1.0
  virtuacommands: virtuaorbs/commands@0.3.0

jobs:
  surveillance-job:
    executor: virtuaorbs/mongoruby_2.6.3
    steps:
      - setup-ruby-environment
      - run:
          name: "Make a watch over the whole infrastructure to detect problems"
          exec: bundle exec ruby watcher.rb
      - store_test_results:
          path: /tmp/surveillance
      - store_artifacts:
          path: /tmp/surveillance
          destination: surveillance

workflows:
  version: 2.1
  watch:
    triggers:
      - schedule:
          cron: "*/10 * * * *"
    jobs:
      - surveillance-job